n1=int(input('Ingresa un numero: '))
n2=int(input('Ingresa otro: '))
suma=n1+n2
print(f"{n1} + {n2} = {suma}")
resta=n1-n2
print(f"{n1} - {n2} = {resta}")
mult=n1*n2
print(f"{n1} * {n2} = {mult}")
div=n1/n2
print(f"{n1} / {n2} = {div}")